name: Cron Job
on:
  schedule:
    - cron: "*/10 * * * *"
  # 手動実行用の記述
  workflow_dispatch:
jobs:
  my_cron_job:
    name: cron job
    runs-on: ubuntu-latest
    steps:
    - name: Hello My Cron Job
      run: echo 'Hello, My Cron Job!'
